services:
  app:
    build:
      context: .
      dockerfile: docker/dev/go/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - .:/app
      - ${GO_MODULES_CACHE:-/tmp/go-modules}:/go/pkg
    environment:
      APP_PORT: 8080
      APP_DB_HOST: postgres
      APP_DB_NAME: app
      APP_DB_USER: gorm
      APP_DB_PASS: 1234
      APP_DB_PORT: 5432
      GOCACHE: /tmp/.cache
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app
    ports:
      - "2345:5432"